name: Inventory_Infrastructure

services:

  endpoint:
    container_name: endpoint
    build: ./Endpoint
    networks:
      - database_network


  database:
    container_name: database
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: temporaryadmin
      POSTGRES_PASSWORD: temporarypassword
      POSTGRES_DB: inventory_db
    volumes:
      - ./Database/data:/var/lib/postgresql
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - database_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporaryadmin -d inventory_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  webapi:
    container_name: webapi
    build: ./WebAPI
    networks:
      - database_network
    ports:
      - "9001:9001"
    depends_on:
      database:
        condition: service_healthy

networks:
  database_network:
    ipam:
      config:
        - subnet: 10.64.0.0/24
          gateway: 10.64.0.1
          aux_addresses:
            endpoint: 10.64.0.2
            webapi: 10.64.0.4
            database: 10.64.0.5

